# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2025. This work has been developed by the National Digital Twin Programme
# and is legally attributed to the Department for Business and Trade (UK) as the governing entity.

"""022_update_regions_view_remove_visual_buffer

Revision ID: 47ed09fc85cc
Revises: e72a7ae5be78
Create Date: 2025-10-24 09:55:13.319383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47ed09fc85cc'
down_revision: Union[str, None] = 'e72a7ae5be78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    
    """ Recreate materialised views for regions"""
    op.execute(
        """
        DROP MATERIALIZED VIEW IF EXISTS iris.uk_region_epc;
    """
    )
    
    op.execute(
        """
        DROP MATERIALIZED VIEW IF EXISTS iris.uk_region_epc_data;
    """
    )
    
    op.execute(
        """
        CREATE MATERIALIZED VIEW IF NOT EXISTS iris.uk_region_epc_data
        AS
        WITH regions_buffered AS(
        SELECT
            name,
            geom_simplified as geometry,
            ST_Transform(  -- convert back to WGS84
                ST_Buffer( -- buffer in metres (because 27700 uses metres)
                    ST_Transform(geom_simplified, 27700), 
                    5000       -- buffer distance in metres
                ),
                4326          -- back to WGS84
            ) AS geometry_buff_5k
        FROM iris.english_region
        UNION ALL
        SELECT
            name,
            geometry,
            ST_Transform(
                ST_Buffer(
                    ST_Transform(geometry, 27700),
                    5000
                ),
                4326
            ) AS geometry_buff_5k
        FROM iris.country_region
        WHERE name = 'Wales')
        SELECT
            r.name AS name,
            SUM(e.total) AS total,
            SUM(e.epc_a) AS epc_a,
            SUM(e.epc_b) AS epc_b,
            SUM(e.epc_c) AS epc_c,
            SUM(e.epc_d) AS epc_d,
            SUM(e.epc_e) AS epc_e,
            SUM(e.epc_f) AS epc_f,
            SUM(e.epc_g) AS epc_g,
            SUM(e.epc_null) AS epc_null,
            r.geometry
        FROM regions_buffered r
        JOIN iris.district_borough_unitary_epc_data e
        ON ST_Contains(r.geometry_buff_5k, ST_Simplify(e.geometry, 0.0001))
        GROUP BY r.name, r.geometry
        WITH NO DATA;
    """
    )
    
    """ Create materialized view containing GeoJSON."""
    op.execute(
        """
        CREATE MATERIALIZED VIEW IF NOT EXISTS iris.uk_region_epc
            TABLESPACE pg_default
            AS
            SELECT jsonb_build_object('type', 'FeatureCollection', 'features', jsonb_agg(jsonb_build_object('type', 'Feature', 'geometry', st_asgeojson(ST_SIMPLIFY(geometry, 0.0001))::json, 'properties', to_jsonb(t.*) - 'geometry'::text))) AS geojson
            FROM iris.uk_region_epc_data t
            WITH NO DATA;
    """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    """ Recreate materialised views for regions"""
    op.execute(
        """
        DROP MATERIALIZED VIEW IF EXISTS iris.uk_region_epc;
    """
    )
    
    op.execute(
        """
        DROP MATERIALIZED VIEW IF EXISTS iris.uk_region_epc_data;
    """
    )
    
    op.execute(
        """
        CREATE MATERIALIZED VIEW IF NOT EXISTS iris.uk_region_epc_data
        AS
        WITH regions_buffered AS(
        SELECT
            name,
            ST_Transform(  -- convert back to WGS84
                ST_Buffer( -- buffer in metres (because 27700 uses metres)
                    ST_Transform(geom_simplified, 27700), 
                    5000       -- buffer distance in metres
                ),
                4326          -- back to WGS84
            ) AS geometry
        FROM iris.english_region
        UNION ALL
        SELECT
            name,
            ST_Transform(
                ST_Buffer(
                    ST_Transform(geometry, 27700),
                    5000
                ),
                4326
            ) AS geometry
        FROM iris.country_region
        WHERE name = 'Wales')
        SELECT
            r.name AS name,
            SUM(e.total) AS total,
            SUM(e.epc_a) AS epc_a,
            SUM(e.epc_b) AS epc_b,
            SUM(e.epc_c) AS epc_c,
            SUM(e.epc_d) AS epc_d,
            SUM(e.epc_e) AS epc_e,
            SUM(e.epc_f) AS epc_f,
            SUM(e.epc_g) AS epc_g,
            SUM(e.epc_null) AS epc_null,
            r.geometry
        FROM regions_buffered r
        JOIN iris.district_borough_unitary_epc_data e
        ON ST_Contains(r.geometry, ST_Simplify(e.geometry, 0.0001))
        GROUP BY r.name, r.geometry
        WITH NO DATA;
    """
    )
    
    """ Create materialized view containing GeoJSON."""
    op.execute(
        """
        CREATE MATERIALIZED VIEW IF NOT EXISTS iris.uk_region_epc
            TABLESPACE pg_default
            AS
            SELECT jsonb_build_object('type', 'FeatureCollection', 'features', jsonb_agg(jsonb_build_object('type', 'Feature', 'geometry', st_asgeojson(ST_SIMPLIFY(geometry, 0.0001))::json, 'properties', to_jsonb(t.*) - 'geometry'::text))) AS geojson
            FROM iris.uk_region_epc_data t
            WITH NO DATA;
    """
    )
