# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2025. This work has been developed by the National Digital Twin Programme
# and is legally attributed to the Department for Business and Trade (UK) as the governing entity.

"""011_create_uk_counties_table_view

Revision ID: d99eb3e1e4ab
Revises: 993c0cf8ea04
Create Date: 2025-08-27 16:38:28.857698

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d99eb3e1e4ab"
down_revision: Union[str, None] = "993c0cf8ea04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade() -> None:
    """Upgrade schema."""
    """ Create id for iris.boundary_line_ceremonial_counties"""
    op.execute(
        """
        CREATE SEQUENCE IF NOT EXISTS iris.boundary_line_ceremonial_counties_fid_seq1
            INCREMENT 1
            START 1
            MINVALUE 1
            MAXVALUE 2147483647
            CACHE 1;
    """
    )

    """ Create table for iris.boundary_line_ceremonial_counties"""
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS iris.boundary_line_ceremonial_counties
            ( 
                fid integer NOT NULL DEFAULT nextval('iris.boundary_line_ceremonial_counties_fid_seq1'::regclass),
                name character varying,
                Area_description character varying,              
                geometry geometry(MultiPolygon,4326),
                CONSTRAINT boundary_line_ceremonial_counties_P PRIMARY KEY (fid)
            )
    """
    )

    """ Create geo index for boundary_line_ceremonial_counties"""
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS boundary_line_ceremonial_counties_geometry_idx
            ON iris.boundary_line_ceremonial_counties USING gist
            (geometry)
            TABLESPACE pg_default;
    """
    )

    op.execute(
        """
        CREATE MATERIALIZED VIEW IF NOT EXISTS iris.boundary_line_ceremonial_counties_epc_data
            AS
            SELECT
                b.name,
                COUNT (a.point) AS total,
                COUNT(CASE WHEN a.epc_rating = 'A' THEN 1 END) AS epc_a,
                COUNT(CASE WHEN a.epc_rating = 'B' THEN 1 END) AS epc_b,
                COUNT(CASE WHEN a.epc_rating = 'C' THEN 1 END) AS epc_c,
                COUNT(CASE WHEN a.epc_rating = 'D' THEN 1 END) AS epc_d,
                COUNT(CASE WHEN a.epc_rating = 'E' THEN 1 END) AS epc_e,
                COUNT(CASE WHEN a.epc_rating = 'F' THEN 1 END) AS epc_f,
                COUNT(CASE WHEN a.epc_rating = 'G' THEN 1 END) AS epc_g,
                COUNT(CASE WHEN a.epc_rating IS NULL THEN 1 END) AS epc_null,
                b.geometry
            FROM iris.building_epc a
            LEFT JOIN iris.boundary_line_ceremonial_counties b
            ON ST_Intersects(b.geometry, a.point)
            GROUP BY b.name, b.geometry
        WITH NO DATA;
    """
    )

    """ Create materialized view containing GeoJSON."""
    op.execute(
        """
        CREATE MATERIALIZED VIEW IF NOT EXISTS iris.boundary_line_ceremonial_counties_epc
            TABLESPACE pg_default
            AS
            SELECT jsonb_build_object('type', 'FeatureCollection', 'features', jsonb_agg(jsonb_build_object('type', 'Feature', 'geometry', st_asgeojson(ST_SIMPLIFY(geometry, 0.0001))::json, 'properties', to_jsonb(t.*) - 'geometry'::text))) AS geojson
            FROM iris.boundary_line_ceremonial_counties_epc_data t
            WITH NO DATA;
    """
    )


def downgrade() -> None:

    op.execute(
        """
        DROP MATERIALIZED VIEW IF EXISTS iris.boundary_line_ceremonial_counties_epc;
    """
    )
    op.execute(
        """
        DROP MATERIALIZED VIEW IF EXISTS iris.boundary_line_ceremonial_counties_epc_data;
    """
    )
    op.execute(
        """
        DROP INDEX IF EXISTS iris.boundary_line_ceremonial_counties_geometry_idx;
    """
    )

    op.execute(
        """
        DROP TABLE IF EXISTS iris.boundary_line_ceremonial_counties;
    """
    )

    op.execute(
        """
        DROP SEQUENCE IF EXISTS iris.boundary_line_ceremonial_counties_fid_seq1;
    """
    )
