#!/bin/bash
set -e

alembic upgrade head
MATERIALIZED_VIEW=iris.wind_driven_rain_projections_geojson TARGET_TABLE=wind_driven_rain_projections GPKG_SOURCE=https://services.arcgis.com/Lq3V5RFuTBC9I7kv/arcgis/rest/services/Annual_Index_of_Wind_Driven_Rain_Projections_5km/FeatureServer/replicafilescache/Annual_Index_of_Wind_Driven_Rain_Projections_5km_-6134910210859057092.gpkg  python load_gpkg_to_postgis.py
MATERIALIZED_VIEW=iris.icing_days_geojson TARGET_TABLE=annual_count_of_icing_days_1991_2020 GPKG_SOURCE=https://services.arcgis.com/Lq3V5RFuTBC9I7kv/arcgis/rest/services/Annual_Count_of_Icing_Days_1991_2020/FeatureServer/replicafilescache/Annual_Count_of_Icing_Days_1991_2020_5977951113111576455.gpkg python load_gpkg_to_postgis.py
MATERIALIZED_VIEW=iris.hot_summer_days_geojson TARGET_TABLE=annual_count_of_hot_summer_days_projections_12km GPKG_SOURCE=https://services.arcgis.com/Lq3V5RFuTBC9I7kv/arcgis/rest/services/Annual_Count_of_Hot_Days___Projections__12km_grid_/FeatureServer/replicafilescache/Annual_Count_of_Hot_Days___Projections__12km_grid__5151054028377652076.gpkg python developer-resources/load_gpkg_to_postgis.py
MATERIALIZED_VIEW=iris.uk_ward_epc TARGET_TABLE=uk_ward GPKG_SOURCE='https://api.os.uk/downloads/v1/products/BoundaryLine/downloads?area=GB&format=GeoPackage&redirect' GPKG_TABLE=district_borough_unitary_ward python developer-resources/load_gpkg_to_postgis.py
python api/main.py --host 0.0.0.0
