apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: iris-write-api-static-secret
spec:
  refreshAfter: 30s
  # path of the secret
  path: applications/iris/write-api
  type: kv-v2
  mount: k8-cluster
  destination:
    # destination k8s secret
    name: iris-write-api-secrets
    create: true
  vaultAuthRef: iris-write-api-vault-auth
