apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: iris-dbms-static-secret
spec:
  refreshAfter: 30s
  # path of the secret
  path: applications/iris/dbms
  type: kv-v2
  mount: k8-cluster
  destination:
    # destination k8s secret
    name: iris-dbms-secrets
    create: true
  vaultAuthRef: iris-dbms-vault-auth
