resources:
  - ../../base

namespace: iris

configMapGenerator:
  - name: iris-write-api-configs
    envs:
      - params.env

patches:
  - path: patches/service-account.yaml
    target:
      kind: ServiceAccount

labels:
  - pairs:
      env: staging

images:
  - name: iris-write-api-image:template
    newName: 503561419905.dkr.ecr.eu-west-2.amazonaws.com/iris/write-api
    newTag: '1736464040'
