name: Frontend CI on PR

on:
  workflow_call:
  pull_request:
    branches:
      - "develop"
    paths:
      - "api/**"
      - "requirements.txt"
      - ".github/workflows/frontend-ci-pr.yml"
      - ".github/workflows/frontend-ci-pr-merge.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: read
  statuses: write # To report GitHub Actions status checks

jobs:
  security-scanning:
    name: Security Scanning
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: "fs"
          scan-ref: .
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
        continue-on-error: true

  docker-build-test-scan:
    name: Build, Docker Build, Test & Scan
    runs-on: ubuntu-latest
    needs: security-scanning
    timeout-minutes: 20
    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    environment: development
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build --secret id=pat_token,env=GITHUB_ACCESS_TOKEN -t iris/api:latest -f Dockerfile .

      - name: Run Trivy Scan on Docker Image
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: "iris/api:latest"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
        continue-on-error: true
